from __future__ import annotations

import uuid
from typing import Any, Optional

from sqlalchemy import Boolean, ForeignKey, Index, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base, TimestampMixin, UUIDPrimaryKey


class Alert(Base, UUIDPrimaryKey, TimestampMixin):
    """
    Generated by alert_worker when SLA conditions are breached.
    No Telegram notifications — stored only in this table (per DO_NOT_BUILD_YET).
    """
    __tablename__ = "alerts"
    __table_args__ = (
        Index("ix_alerts_project_id", "project_id"),
        Index("ix_alerts_is_read", "is_read"),
        Index("ix_alerts_created_at", "created_at"),
    )

    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False
    )
    # 'long_response' | 'many_unanswered'
    type: Mapped[str] = mapped_column(String(100), nullable=False)
    payload: Mapped[Optional[dict[str, Any]]] = mapped_column(JSONB, nullable=True)
    is_read: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default="false"
    )

    project: Mapped[Project] = relationship("Project", back_populates="alerts")
